version: '3.8'

services:
  telegram-mini-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    container_name: telegram-mini-app
    